In [1]:
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 10 16:25:03 2020

@author: Dongwon Lee.
@dongwon.lee@mechbau.uni-stuttgart.de
@ Post-processing after U-net
"""

import tensorflow as tf
print("Num GPUs Available: ", 
      len(tf.config.experimental.list_physical_devices('GPU')))


gpus  = tf.config.experimental.list_physical_devices('GPU')


if gpus:
  # Restrict TensorFlow to only use the first GPUq 
  try:
    tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPU")
  except RuntimeError as e:
    # Visible devices must be set before GPUs have been initialized
    print(e)
    
#%%    
from img_seg import *
from unet_v2_mod import *
from keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator

#%% path setting for prediction tiles

model_v = 'training_model_3d.keras'
#model_v = 'trained_model_U_net_27.keras'

frag_save_path = 'frag_results_3d'
img_size = (32, 32, 32)
num_of_classes = 1

tpath = os.path.join(os.getcwd(), '..') 
test_n = ['org_frag_data_3d']

2025-08-04 18:47:03.765627: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-08-04 18:47:03.779923: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-04 18:47:03.880133: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-08-04 18:47:03.963899: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1754326024.038029  100555 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1754326024.05

Num GPUs Available:  0


2025-08-04 18:47:07.162538: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [3]:
test_data_path = os.path.join(tpath,'sample_data', 'U_net', 'test_data')

#%%
#model = load_model(os.path.join(tpath, 'results', 'U_net', model_v))
#%% 
model = load_model(os.path.join(tpath, 'results', 'U_net', model_v))

#%%
test_datagen = ImageDataGenerator(rescale = 1./255)
test_gen = test_datagen.flow_from_directory(
    test_data_path,  
    classes = test_n,
    color_mode = 'grayscale',
    shuffle = False,
    class_mode = None,
    batch_size = 1,
    target_size = img_size
)


#%% creating predictions

frlist,frpath = readingfiles(os.path.join(tpath,'sample_data', 'U_net', 'test_data'), 'org_frag_data_3d')
frlist.sort()

a = 0
counter = 0
for i in tqdm(range(len(test_gen))):
    #if np.mean(test_gen[i]) != 0:
    #    a += 1
    #if i <= 100:
    #  print(test_gen[i].shape, np.mean(test_gen[i]))
    result = model.predict(test_gen[i], verbose=0)
    #break
    #btemp = io.imread(os.path.join(frpath, frlist[i]))
    print(result.shape)
    atemp = result.squeeze()
    print(atemp.shape)
    atemp[atemp<0] =0
    
    saveCheckImages(atemp,
                    os.path.join(tpath,'results','U_net',frag_save_path),
                    'frag_seg_3d_'+frlist[i])
#print(a)

Found 16928 images belonging to 1 classes.


  0%|                                                                | 1/16928 [00:00<1:52:35,  2.51it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                  | 4/16928 [00:00<43:20,  6.51it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                  | 7/16928 [00:01<34:07,  8.27it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                 | 10/16928 [00:01<30:35,  9.22it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                 | 14/16928 [00:01<28:38,  9.84it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                 | 17/16928 [00:02<28:58,  9.72it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                 | 19/16928 [00:02<29:01,  9.71it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                 | 21/16928 [00:02<32:51,  8.57it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                 | 23/16928 [00:02<31:03,  9.07it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                 | 27/16928 [00:03<28:54,  9.74it/s]

(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)
(1, 32, 32, 32, 1)
(32, 32, 32)


  0%|                                                                 | 28/16928 [00:03<32:59,  8.54it/s]


(1, 32, 32, 32, 1)
(32, 32, 32)


Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7a78cd4b35e0>
Traceback (most recent call last):
  File "/usr/lib/python3.9/weakref.py", line 370, in remove
    def remove(k, selfref=ref(self)):
KeyboardInterrupt: 


KeyboardInterrupt: 

In [11]:
f = io.imread(os.path.join(tpath,'results','U_net',frag_save_path, 'frag_seg_3d_slice_2005_cropped_0000.tif'))
f2 = io.imread(os.path.join(tpath,'sample_data','U_net', 'training_data', 'seg_frag_data_3d', 'CV_file_2017_cropped_0055.tif'))

print(f.shape, np.mean(f))
print(f)

print(f2.shape, np.mean(f2))
print(f2)

(32, 32, 32) 29.715301513671875
[[[114 105  99 ...  98 101 106]
  [103  86  78 ...  75  79  91]
  [ 97  75  66 ...  62  68  82]
  ...
  [ 96  72  63 ...  58  64  81]
  [ 99  79  70 ...  65  72  88]
  [107  93  86 ...  83  88 100]]

 [[107  95  88 ...  85  89  97]
  [ 91  71  63 ...  57  63  79]
  [ 83  58  51 ...  44  50  68]
  ...
  [ 80  54  46 ...  41  47  67]
  [ 85  62  53 ...  49  56  75]
  [ 98  81  72 ...  69  75  91]]

 [[105  91  83 ...  80  84  93]
  [ 87  65  57 ...  52  58  74]
  [ 78  52  45 ...  40  45  63]
  ...
  [ 74  47  39 ...  37  43  62]
  [ 79  54  45 ...  43  50  70]
  [ 94  74  65 ...  62  70  87]]

 ...

 [[106  93  87 ...  85  90  98]
  [ 89  69  63 ...  60  66  83]
  [ 80  57  51 ...  48  55  75]
  ...
  [ 77  52  44 ...  41  49  69]
  [ 82  60  51 ...  47  56  76]
  [ 97  79  71 ...  67  75  92]]

 [[109  98  93 ...  90  95 102]
  [ 94  78  70 ...  67  75  91]
  [ 86  66  58 ...  55  63  82]
  ...
  [ 83  60  52 ...  49  57  78]
  [ 88  69  61 ...  57  65  

In [5]:
f = io.imread(os.path.join(tpath,'results','U_net','frag_results', 'frag_seg_slice_0085_cropped_0044.tif'))

print(f.shape, np.mean(f))
print(f)

(400, 400) 6.50125625
[[  1   0  10 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [147 241 241 ...   0   0   0]
 [105 158 225 ...   0   0   0]
 [128 209 167 ...   0   0   0]]


In [ ]:
#%% path setting for merged files
mfpath = os.path.join(tpath,'results','U_net',frag_save_path)

mflist = os.listdir(mfpath)

merge_save_path = os.path.join('results', 'U_net', 'seg_merged_3d')

filecounter = 0
msavepath = os.path.join(tpath, merge_save_path) 
#%%      
if not os.path.exists(msavepath):
    os.makedirs(msavepath)

print(mflist[:100])
a=b

#%%
filecounter = 0
for iTemp in tqdm(range(int(len(mflist) / 81))):
    #mimg,filecounter = overlap_merge_image((2940,2940),filecounter,img_size,mfpath,mflist)
    mimg,filecounter = overlap_merge_image((2940,2940),(400*9,400*9),
                                           filecounter,400,256,mfpath,mflist)
    slice_number = mflist[filecounter-1].split('_')[3]
    savename = os.path.join(msavepath, "uint8_" + slice_number + ".tif")
    zeroTemp = np.zeros((2940,2940))
    shift_factor = int((400-256)/2/2 + 1)
    zeroTemp[0:2940-shift_factor,0:2940-shift_factor] = mimg[shift_factor:,shift_factor:]
    io.imsave(savename,zeroTemp.astype('uint8'))  